### PR TITLE
Fix variable names

### PR DESCRIPTION
**Pull request by z4ab**
The variable `list` overrides one of python's built-in static classes.  It interferes with autocomplete.

### CODE REVIEW

**Review by stfxcomsci — APPROVED** [review]
Literate programming!!!  Yes I like it.

**Comment by z4ab** [comment]
My first approved pr is a search and replace :)

**Comment by z4ab** [comment]
nvm thats not how that works

**Comment by z4ab** [comment]
Sorting function sorts the original list. This is fixed with the built-in `list.copy` function in 21f421dbb0b11ca40c370dbe0855140f6dbef57a

**Pull request closed without merging**
